import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import Providers from "./admin-dashboard/providers";
import { UserProvider } from "@/context/UserContext";
import { SidebarProvider } from "@/context/SidebarContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body>
        <ThemeProvider>
          <Providers>
            <UserProvider>
              <SidebarProvider>{children}</SidebarProvider>
            </UserProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
